### ISSUE TITLE
Dry listed as a noun

### ISSUE THREAD

**Issue by cefn** [kylestetz/Sentencer#12]
Thanks so much for sentencer. It has made me happy.

To improve the word list one at a time, I can't see any natural context in which `turkish` `dry` `married` `prepared` `separated` `unshielded` or `fired` would be nouns that compose well in sentences, as they read more like adjectives...
https://github.com/kylestetz/Sentencer/blob/cc637cb871638b6e813aca587fa007074713a01c/words/nouns.js#L675

Happy to raise a PR if you agree.

**Comment by kylestetz** [comment]
Glad you like it! I whole-heartedly agree. I welcome any PRs you want to send over 🙂

**Comment by kylestetz** [comment]
Merged your PR and published version `0.2.1`, thanks!
