### ISSUE TITLE
This is so cool!

### ISSUE THREAD

**Issue by castillobg** [kylestetz/Sentencer#4]
This is such a cool project! Thanks for sharing it. Also, awesome project page at http://kylestetz.github.io/Sentencer/

:metal:

**Comment by kylestetz** [comment]
Thank you @castillobg, glad you like it 😊 If you end up using it in a project, I'd love to see it!

**Comment by castillobg** [comment]
@kylestetz I am! [castillobg/chat-snap](https://github.com/castillobg/chat-snap) (live at [chat-snap.herokuapp.com](https://chat-snap.herokuapp.com)). It's a real-time photo-chat for my workshop at this year's [JSConf Colombia](http://jsconf.co). I'm using Sentencer to generate random ids for the chat rooms.
Still a WIP though!
I'm also thinking of doing a golang version for a small project I have. I'll let you know if that happens too 😄

**Comment by kylestetz** [comment]
Oh that's a cool usage! I support you making a golang version and I'll happily link to it in this repo 👌

**Comment by castillobgr** [comment]
Boom, done! Here it is https://github.com/castillobgr/sententia
This was fun to build.

**Comment by lmj0011** [comment]
cool lib, bro. I will try to colab in someway if I get time.
